#!/usr/bin/env bash
# snapshot-context.sh — Download Claude conversation transcripts +
# auto-memory from a sandbox to the host so they survive sandbox rebuilds.
#
# What's captured:
#   /sandbox/.claude/projects/   transcripts (*.jsonl) + per-project auto-memory
#   /sandbox/.claude/sessions/   transient PID→session-uuid mapping (nice-to-have)
#
# What's deliberately NOT captured (regenerated by sandbox-init.sh or
# sandbox-local secrets):
#   .credentials.json, .claude.json, settings.json, plugins/, skills/
#
# Usage:
#   snapshot-context.sh --name s1                 # snapshot a sandbox
#   snapshot-context.sh --name s1 --dest /tmp/x   # different host dest
#
# Default destination is $OSK_ROOT/state/<sandbox-name>/. Subsequent
# snapshots overwrite (atomically via mv). Pass --dest to keep older
# snapshots side-by-side.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OSK_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=_lib.sh
source "${SCRIPT_DIR}/_lib.sh"

NAME=""
DEST=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --name) NAME="$2"; shift 2 ;;
        --dest) DEST="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,18p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) osk::die "unknown arg: $1" ;;
    esac
done

[[ -n "$NAME" ]] || osk::die "--name <sandbox> is required"
[[ -z "$DEST" ]] && DEST="${OSK_ROOT}/state/${NAME}"

osk::require_cmd openshell

if ! openshell sandbox get "$NAME" >/dev/null 2>&1; then
    osk::die "sandbox '$NAME' does not exist"
fi

# Stage to a temp dir, atomically move on success. This avoids leaving
# the destination half-populated if the download fails midway.
STAGING=$(mktemp -d)
trap 'rm -rf "$STAGING"' EXIT
mkdir -p "${STAGING}/projects" "${STAGING}/sessions"

osk::info "snapshotting from sandbox '$NAME'..."

if ! openshell sandbox download "$NAME" /sandbox/.claude/projects "${STAGING}/projects/" >/dev/null 2>&1; then
    osk::die "failed to download /sandbox/.claude/projects (sandbox unreachable or .claude/projects missing)"
fi

openshell sandbox download "$NAME" /sandbox/.claude/sessions "${STAGING}/sessions/" >/dev/null 2>&1 \
    || osk::warn "sessions/ download failed (transient state, non-fatal)"

TRANSCRIPTS=$(find "${STAGING}/projects" -name '*.jsonl' 2>/dev/null | wc -l)
SIZE=$(du -sh "${STAGING}" 2>/dev/null | cut -f1)

mkdir -p "$(dirname "$DEST")"
rm -rf "$DEST"
mv "$STAGING" "$DEST"
trap - EXIT

osk::ok "snapshot: ${TRANSCRIPTS} transcripts, ${SIZE} → ${DEST}"
